- hosts: dev
  become: true
  tasks:
   - copy:
        content: "hello world"
        dest: /var/www/html/index.html

     notify: restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
        enabled: yes

     
